// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package aiocean_authn_v1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// AuthnServiceClient is the client API for AuthnService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type AuthnServiceClient interface {
	LoginWithShopify(ctx context.Context, in *LoginWithShopifyRequest, opts ...grpc.CallOption) (*LoginWithShopifyResponse, error)
	LoginWithShopifyCallback(ctx context.Context, in *LoginWithShopifyCallbackRequest, opts ...grpc.CallOption) (*LoginWithShopifyCallbackResponse, error)
}

type authnServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewAuthnServiceClient(cc grpc.ClientConnInterface) AuthnServiceClient {
	return &authnServiceClient{cc}
}

func (c *authnServiceClient) LoginWithShopify(ctx context.Context, in *LoginWithShopifyRequest, opts ...grpc.CallOption) (*LoginWithShopifyResponse, error) {
	out := new(LoginWithShopifyResponse)
	err := c.cc.Invoke(ctx, "/aiocean.authn.v1.AuthnService/LoginWithShopify", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *authnServiceClient) LoginWithShopifyCallback(ctx context.Context, in *LoginWithShopifyCallbackRequest, opts ...grpc.CallOption) (*LoginWithShopifyCallbackResponse, error) {
	out := new(LoginWithShopifyCallbackResponse)
	err := c.cc.Invoke(ctx, "/aiocean.authn.v1.AuthnService/LoginWithShopifyCallback", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AuthnServiceServer is the server API for AuthnService service.
// All implementations must embed UnimplementedAuthnServiceServer
// for forward compatibility
type AuthnServiceServer interface {
	LoginWithShopify(context.Context, *LoginWithShopifyRequest) (*LoginWithShopifyResponse, error)
	LoginWithShopifyCallback(context.Context, *LoginWithShopifyCallbackRequest) (*LoginWithShopifyCallbackResponse, error)
	mustEmbedUnimplementedAuthnServiceServer()
}

// UnimplementedAuthnServiceServer must be embedded to have forward compatible implementations.
type UnimplementedAuthnServiceServer struct {
}

func (UnimplementedAuthnServiceServer) LoginWithShopify(context.Context, *LoginWithShopifyRequest) (*LoginWithShopifyResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method LoginWithShopify not implemented")
}
func (UnimplementedAuthnServiceServer) LoginWithShopifyCallback(context.Context, *LoginWithShopifyCallbackRequest) (*LoginWithShopifyCallbackResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method LoginWithShopifyCallback not implemented")
}
func (UnimplementedAuthnServiceServer) mustEmbedUnimplementedAuthnServiceServer() {}

// UnsafeAuthnServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AuthnServiceServer will
// result in compilation errors.
type UnsafeAuthnServiceServer interface {
	mustEmbedUnimplementedAuthnServiceServer()
}

func RegisterAuthnServiceServer(s grpc.ServiceRegistrar, srv AuthnServiceServer) {
	s.RegisterService(&AuthnService_ServiceDesc, srv)
}

func _AuthnService_LoginWithShopify_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LoginWithShopifyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthnServiceServer).LoginWithShopify(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/aiocean.authn.v1.AuthnService/LoginWithShopify",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthnServiceServer).LoginWithShopify(ctx, req.(*LoginWithShopifyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AuthnService_LoginWithShopifyCallback_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LoginWithShopifyCallbackRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthnServiceServer).LoginWithShopifyCallback(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/aiocean.authn.v1.AuthnService/LoginWithShopifyCallback",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthnServiceServer).LoginWithShopifyCallback(ctx, req.(*LoginWithShopifyCallbackRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// AuthnService_ServiceDesc is the grpc.ServiceDesc for AuthnService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var AuthnService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "aiocean.authn.v1.AuthnService",
	HandlerType: (*AuthnServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "LoginWithShopify",
			Handler:    _AuthnService_LoginWithShopify_Handler,
		},
		{
			MethodName: "LoginWithShopifyCallback",
			Handler:    _AuthnService_LoginWithShopifyCallback_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "aiocean/authn/v1/authn_service.proto",
}
