// Code generated by protoc-gen-validate. DO NOT EDIT.
// source: aiocean/flag/v1/flag_service.proto

package aiocean_flag_v1

import (
	"bytes"
	"errors"
	"fmt"
	"net"
	"net/mail"
	"net/url"
	"regexp"
	"strings"
	"time"
	"unicode/utf8"

	"google.golang.org/protobuf/types/known/anypb"
)

// ensure the imports are used
var (
	_ = bytes.MinRead
	_ = errors.New("")
	_ = fmt.Print
	_ = utf8.UTFMax
	_ = (*regexp.Regexp)(nil)
	_ = (*strings.Reader)(nil)
	_ = net.IPv4len
	_ = time.Duration(0)
	_ = (*url.URL)(nil)
	_ = (*mail.Address)(nil)
	_ = anypb.Any{}
)

// Validate checks the field values on GetFlagVariationRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, an error is returned.
func (m *GetFlagVariationRequest) Validate() error {
	if m == nil {
		return nil
	}

	// no validation rules for Orn

	return nil
}

// GetFlagVariationRequestValidationError is the validation error returned by
// GetFlagVariationRequest.Validate if the designated constraints aren't met.
type GetFlagVariationRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e GetFlagVariationRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e GetFlagVariationRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e GetFlagVariationRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e GetFlagVariationRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e GetFlagVariationRequestValidationError) ErrorName() string {
	return "GetFlagVariationRequestValidationError"
}

// Error satisfies the builtin error interface
func (e GetFlagVariationRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sGetFlagVariationRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = GetFlagVariationRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = GetFlagVariationRequestValidationError{}

// Validate checks the field values on GetFlagVariationResponse with the rules
// defined in the proto definition for this message. If any rules are
// violated, an error is returned.
func (m *GetFlagVariationResponse) Validate() error {
	if m == nil {
		return nil
	}

	return nil
}

// GetFlagVariationResponseValidationError is the validation error returned by
// GetFlagVariationResponse.Validate if the designated constraints aren't met.
type GetFlagVariationResponseValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e GetFlagVariationResponseValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e GetFlagVariationResponseValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e GetFlagVariationResponseValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e GetFlagVariationResponseValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e GetFlagVariationResponseValidationError) ErrorName() string {
	return "GetFlagVariationResponseValidationError"
}

// Error satisfies the builtin error interface
func (e GetFlagVariationResponseValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sGetFlagVariationResponse.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = GetFlagVariationResponseValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = GetFlagVariationResponseValidationError{}
