// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package aiocean_config_v1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// ConfigServiceClient is the client API for ConfigService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ConfigServiceClient interface {
	GetMongoConfig(ctx context.Context, in *GetMongoConfigRequest, opts ...grpc.CallOption) (*GetMongoConfigResponse, error)
	GetShopifyConfig(ctx context.Context, in *GetShopifyConfigRequest, opts ...grpc.CallOption) (*GetShopifyConfigResponse, error)
	GetSecretConfig(ctx context.Context, in *GetSecretConfigRequest, opts ...grpc.CallOption) (*GetSecretConfigResponse, error)
}

type configServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewConfigServiceClient(cc grpc.ClientConnInterface) ConfigServiceClient {
	return &configServiceClient{cc}
}

func (c *configServiceClient) GetMongoConfig(ctx context.Context, in *GetMongoConfigRequest, opts ...grpc.CallOption) (*GetMongoConfigResponse, error) {
	out := new(GetMongoConfigResponse)
	err := c.cc.Invoke(ctx, "/aiocean.config.v1.ConfigService/GetMongoConfig", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *configServiceClient) GetShopifyConfig(ctx context.Context, in *GetShopifyConfigRequest, opts ...grpc.CallOption) (*GetShopifyConfigResponse, error) {
	out := new(GetShopifyConfigResponse)
	err := c.cc.Invoke(ctx, "/aiocean.config.v1.ConfigService/GetShopifyConfig", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *configServiceClient) GetSecretConfig(ctx context.Context, in *GetSecretConfigRequest, opts ...grpc.CallOption) (*GetSecretConfigResponse, error) {
	out := new(GetSecretConfigResponse)
	err := c.cc.Invoke(ctx, "/aiocean.config.v1.ConfigService/GetSecretConfig", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ConfigServiceServer is the server API for ConfigService service.
// All implementations must embed UnimplementedConfigServiceServer
// for forward compatibility
type ConfigServiceServer interface {
	GetMongoConfig(context.Context, *GetMongoConfigRequest) (*GetMongoConfigResponse, error)
	GetShopifyConfig(context.Context, *GetShopifyConfigRequest) (*GetShopifyConfigResponse, error)
	GetSecretConfig(context.Context, *GetSecretConfigRequest) (*GetSecretConfigResponse, error)
	mustEmbedUnimplementedConfigServiceServer()
}

// UnimplementedConfigServiceServer must be embedded to have forward compatible implementations.
type UnimplementedConfigServiceServer struct {
}

func (UnimplementedConfigServiceServer) GetMongoConfig(context.Context, *GetMongoConfigRequest) (*GetMongoConfigResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetMongoConfig not implemented")
}
func (UnimplementedConfigServiceServer) GetShopifyConfig(context.Context, *GetShopifyConfigRequest) (*GetShopifyConfigResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetShopifyConfig not implemented")
}
func (UnimplementedConfigServiceServer) GetSecretConfig(context.Context, *GetSecretConfigRequest) (*GetSecretConfigResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetSecretConfig not implemented")
}
func (UnimplementedConfigServiceServer) mustEmbedUnimplementedConfigServiceServer() {}

// UnsafeConfigServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ConfigServiceServer will
// result in compilation errors.
type UnsafeConfigServiceServer interface {
	mustEmbedUnimplementedConfigServiceServer()
}

func RegisterConfigServiceServer(s grpc.ServiceRegistrar, srv ConfigServiceServer) {
	s.RegisterService(&ConfigService_ServiceDesc, srv)
}

func _ConfigService_GetMongoConfig_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetMongoConfigRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ConfigServiceServer).GetMongoConfig(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/aiocean.config.v1.ConfigService/GetMongoConfig",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ConfigServiceServer).GetMongoConfig(ctx, req.(*GetMongoConfigRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ConfigService_GetShopifyConfig_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetShopifyConfigRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ConfigServiceServer).GetShopifyConfig(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/aiocean.config.v1.ConfigService/GetShopifyConfig",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ConfigServiceServer).GetShopifyConfig(ctx, req.(*GetShopifyConfigRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ConfigService_GetSecretConfig_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetSecretConfigRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ConfigServiceServer).GetSecretConfig(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/aiocean.config.v1.ConfigService/GetSecretConfig",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ConfigServiceServer).GetSecretConfig(ctx, req.(*GetSecretConfigRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// ConfigService_ServiceDesc is the grpc.ServiceDesc for ConfigService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ConfigService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "aiocean.config.v1.ConfigService",
	HandlerType: (*ConfigServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetMongoConfig",
			Handler:    _ConfigService_GetMongoConfig_Handler,
		},
		{
			MethodName: "GetShopifyConfig",
			Handler:    _ConfigService_GetShopifyConfig_Handler,
		},
		{
			MethodName: "GetSecretConfig",
			Handler:    _ConfigService_GetSecretConfig_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "aiocean/config/v1/config_service.proto",
}
