// Code generated by protoc-gen-validate. DO NOT EDIT.
// source: aiocean/polvo/v1/polvo_service.proto

package aiocean_polvo_v1

import (
	"bytes"
	"errors"
	"fmt"
	"net"
	"net/mail"
	"net/url"
	"regexp"
	"strings"
	"time"
	"unicode/utf8"

	"google.golang.org/protobuf/types/known/anypb"
)

// ensure the imports are used
var (
	_ = bytes.MinRead
	_ = errors.New("")
	_ = fmt.Print
	_ = utf8.UTFMax
	_ = (*regexp.Regexp)(nil)
	_ = (*strings.Reader)(nil)
	_ = net.IPv4len
	_ = time.Duration(0)
	_ = (*url.URL)(nil)
	_ = (*mail.Address)(nil)
	_ = anypb.Any{}
)

// Validate checks the field values on ListPackagesRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, an error is returned.
func (m *ListPackagesRequest) Validate() error {
	if m == nil {
		return nil
	}

	if !_ListPackagesRequest_ApplicationOrn_Pattern.MatchString(m.GetApplicationOrn()) {
		return ListPackagesRequestValidationError{
			field:  "ApplicationOrn",
			reason: "value does not match regex pattern \"(?m)^polvo.aiocean.services/applications/[^/]+/packages$\"",
		}
	}

	return nil
}

// ListPackagesRequestValidationError is the validation error returned by
// ListPackagesRequest.Validate if the designated constraints aren't met.
type ListPackagesRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e ListPackagesRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e ListPackagesRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e ListPackagesRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e ListPackagesRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e ListPackagesRequestValidationError) ErrorName() string {
	return "ListPackagesRequestValidationError"
}

// Error satisfies the builtin error interface
func (e ListPackagesRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sListPackagesRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = ListPackagesRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = ListPackagesRequestValidationError{}

var _ListPackagesRequest_ApplicationOrn_Pattern = regexp.MustCompile("(?m)^polvo.aiocean.services/applications/[^/]+/packages$")

// Validate checks the field values on ListPackagesResponse with the rules
// defined in the proto definition for this message. If any rules are
// violated, an error is returned.
func (m *ListPackagesResponse) Validate() error {
	if m == nil {
		return nil
	}

	for idx, item := range m.GetPackages() {
		_, _ = idx, item

		if v, ok := interface{}(item).(interface{ Validate() error }); ok {
			if err := v.Validate(); err != nil {
				return ListPackagesResponseValidationError{
					field:  fmt.Sprintf("Packages[%v]", idx),
					reason: "embedded message failed validation",
					cause:  err,
				}
			}
		}

	}

	return nil
}

// ListPackagesResponseValidationError is the validation error returned by
// ListPackagesResponse.Validate if the designated constraints aren't met.
type ListPackagesResponseValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e ListPackagesResponseValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e ListPackagesResponseValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e ListPackagesResponseValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e ListPackagesResponseValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e ListPackagesResponseValidationError) ErrorName() string {
	return "ListPackagesResponseValidationError"
}

// Error satisfies the builtin error interface
func (e ListPackagesResponseValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sListPackagesResponse.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = ListPackagesResponseValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = ListPackagesResponseValidationError{}

// Validate checks the field values on GetPackageRequest with the rules defined
// in the proto definition for this message. If any rules are violated, an
// error is returned.
func (m *GetPackageRequest) Validate() error {
	if m == nil {
		return nil
	}

	if !_GetPackageRequest_PackageOrn_Pattern.MatchString(m.GetPackageOrn()) {
		return GetPackageRequestValidationError{
			field:  "PackageOrn",
			reason: "value does not match regex pattern \"(?m)^polvo.aiocean.services/applications/[^/]+/packages/[^/]+$\"",
		}
	}

	return nil
}

// GetPackageRequestValidationError is the validation error returned by
// GetPackageRequest.Validate if the designated constraints aren't met.
type GetPackageRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e GetPackageRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e GetPackageRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e GetPackageRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e GetPackageRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e GetPackageRequestValidationError) ErrorName() string {
	return "GetPackageRequestValidationError"
}

// Error satisfies the builtin error interface
func (e GetPackageRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sGetPackageRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = GetPackageRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = GetPackageRequestValidationError{}

var _GetPackageRequest_PackageOrn_Pattern = regexp.MustCompile("(?m)^polvo.aiocean.services/applications/[^/]+/packages/[^/]+$")

// Validate checks the field values on GetPackageResponse with the rules
// defined in the proto definition for this message. If any rules are
// violated, an error is returned.
func (m *GetPackageResponse) Validate() error {
	if m == nil {
		return nil
	}

	if v, ok := interface{}(m.GetPackage()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return GetPackageResponseValidationError{
				field:  "Package",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	return nil
}

// GetPackageResponseValidationError is the validation error returned by
// GetPackageResponse.Validate if the designated constraints aren't met.
type GetPackageResponseValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e GetPackageResponseValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e GetPackageResponseValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e GetPackageResponseValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e GetPackageResponseValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e GetPackageResponseValidationError) ErrorName() string {
	return "GetPackageResponseValidationError"
}

// Error satisfies the builtin error interface
func (e GetPackageResponseValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sGetPackageResponse.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = GetPackageResponseValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = GetPackageResponseValidationError{}

// Validate checks the field values on CreatePackageRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, an error is returned.
func (m *CreatePackageRequest) Validate() error {
	if m == nil {
		return nil
	}

	if v, ok := interface{}(m.GetPackage()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return CreatePackageRequestValidationError{
				field:  "Package",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	return nil
}

// CreatePackageRequestValidationError is the validation error returned by
// CreatePackageRequest.Validate if the designated constraints aren't met.
type CreatePackageRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e CreatePackageRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e CreatePackageRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e CreatePackageRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e CreatePackageRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e CreatePackageRequestValidationError) ErrorName() string {
	return "CreatePackageRequestValidationError"
}

// Error satisfies the builtin error interface
func (e CreatePackageRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sCreatePackageRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = CreatePackageRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = CreatePackageRequestValidationError{}

// Validate checks the field values on CreatePackageResponse with the rules
// defined in the proto definition for this message. If any rules are
// violated, an error is returned.
func (m *CreatePackageResponse) Validate() error {
	if m == nil {
		return nil
	}

	if v, ok := interface{}(m.GetPackage()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return CreatePackageResponseValidationError{
				field:  "Package",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	return nil
}

// CreatePackageResponseValidationError is the validation error returned by
// CreatePackageResponse.Validate if the designated constraints aren't met.
type CreatePackageResponseValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e CreatePackageResponseValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e CreatePackageResponseValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e CreatePackageResponseValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e CreatePackageResponseValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e CreatePackageResponseValidationError) ErrorName() string {
	return "CreatePackageResponseValidationError"
}

// Error satisfies the builtin error interface
func (e CreatePackageResponseValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sCreatePackageResponse.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = CreatePackageResponseValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = CreatePackageResponseValidationError{}

// Validate checks the field values on ListVersionsRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, an error is returned.
func (m *ListVersionsRequest) Validate() error {
	if m == nil {
		return nil
	}

	// no validation rules for PackageOrn

	return nil
}

// ListVersionsRequestValidationError is the validation error returned by
// ListVersionsRequest.Validate if the designated constraints aren't met.
type ListVersionsRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e ListVersionsRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e ListVersionsRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e ListVersionsRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e ListVersionsRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e ListVersionsRequestValidationError) ErrorName() string {
	return "ListVersionsRequestValidationError"
}

// Error satisfies the builtin error interface
func (e ListVersionsRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sListVersionsRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = ListVersionsRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = ListVersionsRequestValidationError{}

// Validate checks the field values on ListVersionsResponse with the rules
// defined in the proto definition for this message. If any rules are
// violated, an error is returned.
func (m *ListVersionsResponse) Validate() error {
	if m == nil {
		return nil
	}

	for idx, item := range m.GetVersions() {
		_, _ = idx, item

		if v, ok := interface{}(item).(interface{ Validate() error }); ok {
			if err := v.Validate(); err != nil {
				return ListVersionsResponseValidationError{
					field:  fmt.Sprintf("Versions[%v]", idx),
					reason: "embedded message failed validation",
					cause:  err,
				}
			}
		}

	}

	return nil
}

// ListVersionsResponseValidationError is the validation error returned by
// ListVersionsResponse.Validate if the designated constraints aren't met.
type ListVersionsResponseValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e ListVersionsResponseValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e ListVersionsResponseValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e ListVersionsResponseValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e ListVersionsResponseValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e ListVersionsResponseValidationError) ErrorName() string {
	return "ListVersionsResponseValidationError"
}

// Error satisfies the builtin error interface
func (e ListVersionsResponseValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sListVersionsResponse.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = ListVersionsResponseValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = ListVersionsResponseValidationError{}

// Validate checks the field values on GetVersionRequest with the rules defined
// in the proto definition for this message. If any rules are violated, an
// error is returned.
func (m *GetVersionRequest) Validate() error {
	if m == nil {
		return nil
	}

	// no validation rules for VersionOrn

	return nil
}

// GetVersionRequestValidationError is the validation error returned by
// GetVersionRequest.Validate if the designated constraints aren't met.
type GetVersionRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e GetVersionRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e GetVersionRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e GetVersionRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e GetVersionRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e GetVersionRequestValidationError) ErrorName() string {
	return "GetVersionRequestValidationError"
}

// Error satisfies the builtin error interface
func (e GetVersionRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sGetVersionRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = GetVersionRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = GetVersionRequestValidationError{}

// Validate checks the field values on GetVersionResponse with the rules
// defined in the proto definition for this message. If any rules are
// violated, an error is returned.
func (m *GetVersionResponse) Validate() error {
	if m == nil {
		return nil
	}

	if v, ok := interface{}(m.GetVersion()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return GetVersionResponseValidationError{
				field:  "Version",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	return nil
}

// GetVersionResponseValidationError is the validation error returned by
// GetVersionResponse.Validate if the designated constraints aren't met.
type GetVersionResponseValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e GetVersionResponseValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e GetVersionResponseValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e GetVersionResponseValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e GetVersionResponseValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e GetVersionResponseValidationError) ErrorName() string {
	return "GetVersionResponseValidationError"
}

// Error satisfies the builtin error interface
func (e GetVersionResponseValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sGetVersionResponse.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = GetVersionResponseValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = GetVersionResponseValidationError{}

// Validate checks the field values on CreateVersionRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, an error is returned.
func (m *CreateVersionRequest) Validate() error {
	if m == nil {
		return nil
	}

	if v, ok := interface{}(m.GetVersion()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return CreateVersionRequestValidationError{
				field:  "Version",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	return nil
}

// CreateVersionRequestValidationError is the validation error returned by
// CreateVersionRequest.Validate if the designated constraints aren't met.
type CreateVersionRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e CreateVersionRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e CreateVersionRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e CreateVersionRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e CreateVersionRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e CreateVersionRequestValidationError) ErrorName() string {
	return "CreateVersionRequestValidationError"
}

// Error satisfies the builtin error interface
func (e CreateVersionRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sCreateVersionRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = CreateVersionRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = CreateVersionRequestValidationError{}

// Validate checks the field values on CreateVersionResponse with the rules
// defined in the proto definition for this message. If any rules are
// violated, an error is returned.
func (m *CreateVersionResponse) Validate() error {
	if m == nil {
		return nil
	}

	if v, ok := interface{}(m.GetVersion()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return CreateVersionResponseValidationError{
				field:  "Version",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	return nil
}

// CreateVersionResponseValidationError is the validation error returned by
// CreateVersionResponse.Validate if the designated constraints aren't met.
type CreateVersionResponseValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e CreateVersionResponseValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e CreateVersionResponseValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e CreateVersionResponseValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e CreateVersionResponseValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e CreateVersionResponseValidationError) ErrorName() string {
	return "CreateVersionResponseValidationError"
}

// Error satisfies the builtin error interface
func (e CreateVersionResponseValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sCreateVersionResponse.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = CreateVersionResponseValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = CreateVersionResponseValidationError{}

// Validate checks the field values on UpdatePackageRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, an error is returned.
func (m *UpdatePackageRequest) Validate() error {
	if m == nil {
		return nil
	}

	// no validation rules for PackageOrn

	if v, ok := interface{}(m.GetPackage()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return UpdatePackageRequestValidationError{
				field:  "Package",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	if v, ok := interface{}(m.GetUpdateMask()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return UpdatePackageRequestValidationError{
				field:  "UpdateMask",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	return nil
}

// UpdatePackageRequestValidationError is the validation error returned by
// UpdatePackageRequest.Validate if the designated constraints aren't met.
type UpdatePackageRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e UpdatePackageRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e UpdatePackageRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e UpdatePackageRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e UpdatePackageRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e UpdatePackageRequestValidationError) ErrorName() string {
	return "UpdatePackageRequestValidationError"
}

// Error satisfies the builtin error interface
func (e UpdatePackageRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sUpdatePackageRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = UpdatePackageRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = UpdatePackageRequestValidationError{}

// Validate checks the field values on UpdatePackageResponse with the rules
// defined in the proto definition for this message. If any rules are
// violated, an error is returned.
func (m *UpdatePackageResponse) Validate() error {
	if m == nil {
		return nil
	}

	if v, ok := interface{}(m.GetPackage()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return UpdatePackageResponseValidationError{
				field:  "Package",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	return nil
}

// UpdatePackageResponseValidationError is the validation error returned by
// UpdatePackageResponse.Validate if the designated constraints aren't met.
type UpdatePackageResponseValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e UpdatePackageResponseValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e UpdatePackageResponseValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e UpdatePackageResponseValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e UpdatePackageResponseValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e UpdatePackageResponseValidationError) ErrorName() string {
	return "UpdatePackageResponseValidationError"
}

// Error satisfies the builtin error interface
func (e UpdatePackageResponseValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sUpdatePackageResponse.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = UpdatePackageResponseValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = UpdatePackageResponseValidationError{}

// Validate checks the field values on UpdateVersionRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, an error is returned.
func (m *UpdateVersionRequest) Validate() error {
	if m == nil {
		return nil
	}

	// no validation rules for VersionOrn

	if v, ok := interface{}(m.GetVersion()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return UpdateVersionRequestValidationError{
				field:  "Version",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	if v, ok := interface{}(m.GetUpdateMask()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return UpdateVersionRequestValidationError{
				field:  "UpdateMask",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	return nil
}

// UpdateVersionRequestValidationError is the validation error returned by
// UpdateVersionRequest.Validate if the designated constraints aren't met.
type UpdateVersionRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e UpdateVersionRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e UpdateVersionRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e UpdateVersionRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e UpdateVersionRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e UpdateVersionRequestValidationError) ErrorName() string {
	return "UpdateVersionRequestValidationError"
}

// Error satisfies the builtin error interface
func (e UpdateVersionRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sUpdateVersionRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = UpdateVersionRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = UpdateVersionRequestValidationError{}

// Validate checks the field values on UpdateVersionResponse with the rules
// defined in the proto definition for this message. If any rules are
// violated, an error is returned.
func (m *UpdateVersionResponse) Validate() error {
	if m == nil {
		return nil
	}

	if v, ok := interface{}(m.GetVersion()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return UpdateVersionResponseValidationError{
				field:  "Version",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	return nil
}

// UpdateVersionResponseValidationError is the validation error returned by
// UpdateVersionResponse.Validate if the designated constraints aren't met.
type UpdateVersionResponseValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e UpdateVersionResponseValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e UpdateVersionResponseValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e UpdateVersionResponseValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e UpdateVersionResponseValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e UpdateVersionResponseValidationError) ErrorName() string {
	return "UpdateVersionResponseValidationError"
}

// Error satisfies the builtin error interface
func (e UpdateVersionResponseValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sUpdateVersionResponse.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = UpdateVersionResponseValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = UpdateVersionResponseValidationError{}

// Validate checks the field values on ListBuildsRequest with the rules defined
// in the proto definition for this message. If any rules are violated, an
// error is returned.
func (m *ListBuildsRequest) Validate() error {
	if m == nil {
		return nil
	}

	if !_ListBuildsRequest_VersionOrn_Pattern.MatchString(m.GetVersionOrn()) {
		return ListBuildsRequestValidationError{
			field:  "VersionOrn",
			reason: "value does not match regex pattern \"(?m)^polvo.aiocean.services/applications/[^/]+/packages/[^/]+/versions/[^/]+$\"",
		}
	}

	return nil
}

// ListBuildsRequestValidationError is the validation error returned by
// ListBuildsRequest.Validate if the designated constraints aren't met.
type ListBuildsRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e ListBuildsRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e ListBuildsRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e ListBuildsRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e ListBuildsRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e ListBuildsRequestValidationError) ErrorName() string {
	return "ListBuildsRequestValidationError"
}

// Error satisfies the builtin error interface
func (e ListBuildsRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sListBuildsRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = ListBuildsRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = ListBuildsRequestValidationError{}

var _ListBuildsRequest_VersionOrn_Pattern = regexp.MustCompile("(?m)^polvo.aiocean.services/applications/[^/]+/packages/[^/]+/versions/[^/]+$")

// Validate checks the field values on ListBuildsResponse with the rules
// defined in the proto definition for this message. If any rules are
// violated, an error is returned.
func (m *ListBuildsResponse) Validate() error {
	if m == nil {
		return nil
	}

	for idx, item := range m.GetBuilds() {
		_, _ = idx, item

		if v, ok := interface{}(item).(interface{ Validate() error }); ok {
			if err := v.Validate(); err != nil {
				return ListBuildsResponseValidationError{
					field:  fmt.Sprintf("Builds[%v]", idx),
					reason: "embedded message failed validation",
					cause:  err,
				}
			}
		}

	}

	return nil
}

// ListBuildsResponseValidationError is the validation error returned by
// ListBuildsResponse.Validate if the designated constraints aren't met.
type ListBuildsResponseValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e ListBuildsResponseValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e ListBuildsResponseValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e ListBuildsResponseValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e ListBuildsResponseValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e ListBuildsResponseValidationError) ErrorName() string {
	return "ListBuildsResponseValidationError"
}

// Error satisfies the builtin error interface
func (e ListBuildsResponseValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sListBuildsResponse.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = ListBuildsResponseValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = ListBuildsResponseValidationError{}

// Validate checks the field values on GetBuildRequest with the rules defined
// in the proto definition for this message. If any rules are violated, an
// error is returned.
func (m *GetBuildRequest) Validate() error {
	if m == nil {
		return nil
	}

	if !_GetBuildRequest_BuildOrn_Pattern.MatchString(m.GetBuildOrn()) {
		return GetBuildRequestValidationError{
			field:  "BuildOrn",
			reason: "value does not match regex pattern \"(?m)^polvo.aiocean.services/applications/[^/]+/packages/[^/]+/versions/[^/]+/builds/[^/]+$\"",
		}
	}

	return nil
}

// GetBuildRequestValidationError is the validation error returned by
// GetBuildRequest.Validate if the designated constraints aren't met.
type GetBuildRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e GetBuildRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e GetBuildRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e GetBuildRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e GetBuildRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e GetBuildRequestValidationError) ErrorName() string { return "GetBuildRequestValidationError" }

// Error satisfies the builtin error interface
func (e GetBuildRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sGetBuildRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = GetBuildRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = GetBuildRequestValidationError{}

var _GetBuildRequest_BuildOrn_Pattern = regexp.MustCompile("(?m)^polvo.aiocean.services/applications/[^/]+/packages/[^/]+/versions/[^/]+/builds/[^/]+$")

// Validate checks the field values on GetBuildResponse with the rules defined
// in the proto definition for this message. If any rules are violated, an
// error is returned.
func (m *GetBuildResponse) Validate() error {
	if m == nil {
		return nil
	}

	if v, ok := interface{}(m.GetBuild()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return GetBuildResponseValidationError{
				field:  "Build",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	return nil
}

// GetBuildResponseValidationError is the validation error returned by
// GetBuildResponse.Validate if the designated constraints aren't met.
type GetBuildResponseValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e GetBuildResponseValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e GetBuildResponseValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e GetBuildResponseValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e GetBuildResponseValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e GetBuildResponseValidationError) ErrorName() string { return "GetBuildResponseValidationError" }

// Error satisfies the builtin error interface
func (e GetBuildResponseValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sGetBuildResponse.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = GetBuildResponseValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = GetBuildResponseValidationError{}

// Validate checks the field values on CreateBuildRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, an error is returned.
func (m *CreateBuildRequest) Validate() error {
	if m == nil {
		return nil
	}

	if v, ok := interface{}(m.GetBuild()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return CreateBuildRequestValidationError{
				field:  "Build",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	return nil
}

// CreateBuildRequestValidationError is the validation error returned by
// CreateBuildRequest.Validate if the designated constraints aren't met.
type CreateBuildRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e CreateBuildRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e CreateBuildRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e CreateBuildRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e CreateBuildRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e CreateBuildRequestValidationError) ErrorName() string {
	return "CreateBuildRequestValidationError"
}

// Error satisfies the builtin error interface
func (e CreateBuildRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sCreateBuildRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = CreateBuildRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = CreateBuildRequestValidationError{}

// Validate checks the field values on CreateBuildResponse with the rules
// defined in the proto definition for this message. If any rules are
// violated, an error is returned.
func (m *CreateBuildResponse) Validate() error {
	if m == nil {
		return nil
	}

	if v, ok := interface{}(m.GetBuild()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return CreateBuildResponseValidationError{
				field:  "Build",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	return nil
}

// CreateBuildResponseValidationError is the validation error returned by
// CreateBuildResponse.Validate if the designated constraints aren't met.
type CreateBuildResponseValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e CreateBuildResponseValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e CreateBuildResponseValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e CreateBuildResponseValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e CreateBuildResponseValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e CreateBuildResponseValidationError) ErrorName() string {
	return "CreateBuildResponseValidationError"
}

// Error satisfies the builtin error interface
func (e CreateBuildResponseValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sCreateBuildResponse.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = CreateBuildResponseValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = CreateBuildResponseValidationError{}

// Validate checks the field values on UpdateBuildRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, an error is returned.
func (m *UpdateBuildRequest) Validate() error {
	if m == nil {
		return nil
	}

	// no validation rules for BuildOrn

	if v, ok := interface{}(m.GetBuild()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return UpdateBuildRequestValidationError{
				field:  "Build",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	if v, ok := interface{}(m.GetUpdateMask()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return UpdateBuildRequestValidationError{
				field:  "UpdateMask",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	return nil
}

// UpdateBuildRequestValidationError is the validation error returned by
// UpdateBuildRequest.Validate if the designated constraints aren't met.
type UpdateBuildRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e UpdateBuildRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e UpdateBuildRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e UpdateBuildRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e UpdateBuildRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e UpdateBuildRequestValidationError) ErrorName() string {
	return "UpdateBuildRequestValidationError"
}

// Error satisfies the builtin error interface
func (e UpdateBuildRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sUpdateBuildRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = UpdateBuildRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = UpdateBuildRequestValidationError{}

// Validate checks the field values on UpdateBuildResponse with the rules
// defined in the proto definition for this message. If any rules are
// violated, an error is returned.
func (m *UpdateBuildResponse) Validate() error {
	if m == nil {
		return nil
	}

	if v, ok := interface{}(m.GetBuild()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return UpdateBuildResponseValidationError{
				field:  "Build",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	return nil
}

// UpdateBuildResponseValidationError is the validation error returned by
// UpdateBuildResponse.Validate if the designated constraints aren't met.
type UpdateBuildResponseValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e UpdateBuildResponseValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e UpdateBuildResponseValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e UpdateBuildResponseValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e UpdateBuildResponseValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e UpdateBuildResponseValidationError) ErrorName() string {
	return "UpdateBuildResponseValidationError"
}

// Error satisfies the builtin error interface
func (e UpdateBuildResponseValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sUpdateBuildResponse.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = UpdateBuildResponseValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = UpdateBuildResponseValidationError{}
